#!/usr/bin/env bash

# Argument provide, ping the IP address 5 times.
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# ping IP address 5 times
ping -c 5 "$1"
